const yachtsData = {
  "azure-dream": {
    name: "Azure Dream",
    type: "Motor Yacht",
    price: "€ 8,500,000",
    length: "45m (147')",
    guests: "12 Guests",
    cabins: "6 Cabins",
    year: "2021",
    builder: "Oceanco",
    speed: "22 Knots",
    description: "Azure Dream represents the pinnacle of modern motor yacht design. Delivered in 2021, she features expansive deck spaces, a beach club, and a breathtaking interior designed by renowned Italian studio. Her master suite on the main deck offers panoramic views and an absolute sanctuary of luxury. With zero-speed stabilizers, she ensures maximum comfort both underway and at anchor.",
    mainImage: "yacht3.png",
    gallery: ["interior_salon.png", "interior_cabin.png", "deck_lounge.png", "yacht3.png"]
  },
  "oceanus": {
    name: "Oceanus",
    type: "Motor Yacht",
    price: "€ 2,200,000",
    length: "28m (92')",
    guests: "8 Guests",
    cabins: "4 Cabins",
    year: "2018",
    builder: "Sunseeker",
    speed: "28 Knots",
    description: "Oceanus is a sleek and sporty performance yacht perfect for Mediterranean cruising. She features a large flybridge with a wet bar, a submersible bathing platform, and contemporary light oak interiors. Fast, agile, and impeccably maintained by her single owner since new.",
    mainImage: "yacht1.png",
    gallery: ["deck_lounge.png", "interior_salon.png", "interior_cabin.png", "yacht1.png"]
  },
  "ocean-dancer": {
    name: "Ocean Dancer",
    type: "Sailing Yacht",
    price: "€ 1,400,000",
    length: "24m (78')",
    guests: "6 Guests",
    cabins: "3 Cabins",
    year: "2015",
    builder: "Nautor Swan",
    speed: "12 Knots",
    description: "A beautiful bluewater cruiser offering the perfect blend of performance and luxury. Ocean Dancer features a carbon mast, automated sailing systems, and a timeless teak interior. Ideal for an owner-operator or a small crew, she is ready to cross oceans in style and safety.",
    mainImage: "yacht2.png",
    gallery: ["interior_cabin.png", "deck_lounge.png", "interior_salon.png", "yacht2.png"]
  },
  "azura": {
    name: "Azura",
    type: "Catamaran",
    price: "€ 890,000",
    length: "18m (59')",
    guests: "8 Guests",
    cabins: "4 Cabins",
    year: "2020",
    builder: "Fountaine Pajot",
    speed: "10 Knots",
    description: "Azura offers incredible volume and stability, making her the perfect platform for island hopping. Her shallow draft allows access to the most secluded anchorages. Features include a large flybridge lounge, seamless indoor-outdoor living, and fuel-efficient cruising capabilities.",
    mainImage: "yacht4.png",
    gallery: ["interior_salon.png", "deck_lounge.png", "interior_cabin.png", "yacht4.png"]
  },
  "aurora": {
    name: "Aurora",
    type: "Motor Yacht",
    price: "€ 4,750,000",
    length: "35m (115')",
    guests: "10 Guests",
    cabins: "5 Cabins",
    year: "2022",
    builder: "Azimut",
    speed: "26 Knots",
    description: "Aurora is a stunning example of Italian craftsmanship and innovative design. Her extensive use of carbon fiber reduces weight and increases interior volume. Highlights include a forward deck lounge, a massive flybridge, and floor-to-ceiling windows in the main salon.",
    mainImage: "yacht5.png",
    gallery: ["deck_lounge.png", "interior_salon.png", "interior_cabin.png", "yacht5.png"]
  },
  "aegean-soul": {
    name: "Aegean Soul",
    type: "Sailing Yacht",
    price: "€ 980,000",
    length: "20m (65')",
    guests: "6 Guests",
    cabins: "3 Cabins",
    year: "2012",
    builder: "Custom Classic",
    speed: "9 Knots",
    description: "A true gentleman's sailing yacht. Aegean Soul combines the romantic aesthetics of classic wooden boat building with modern navigation and comfort systems. Varnished teak, brass fittings, and a cozy interior make her a unique and head-turning vessel wherever she sails.",
    mainImage: "yacht6.png",
    gallery: ["interior_cabin.png", "interior_salon.png", "deck_lounge.png", "yacht6.png"]
  },
  "aquarius": {
    name: "Aquarius",
    type: "Superyacht",
    price: "€ 24,000,000",
    length: "60m (196')",
    guests: "16 Guests",
    cabins: "8 Cabins",
    year: "2020",
    builder: "Lürssen",
    speed: "16 Knots",
    description: "Aquarius is a masterpiece of custom yacht building. Designed for ultimate luxury and global exploration, she features a helipad, a massive beach club with fold-down terraces, a glass-bottom pool, and a dedicated spa deck. A rare opportunity to acquire a pedigree superyacht without the wait.",
    mainImage: "yacht7.png",
    gallery: ["interior_salon.png", "deck_lounge.png", "interior_cabin.png", "yacht7.png"]
  },
  "velocite": {
    name: "Velocité",
    type: "Sailing Yacht",
    price: "€ 3,200,000",
    length: "30m (98')",
    guests: "8 Guests",
    cabins: "4 Cabins",
    year: "2019",
    builder: "Wally Yachts",
    speed: "15 Knots",
    description: "Built for speed and pure sailing exhilaration, Velocité is a carbon fiber rocket. Despite her racing pedigree, her interior offers uncompromising minimalist luxury. Push-button sailing allows her to be operated with a minimal crew, offering a thrilling yet comfortable experience.",
    mainImage: "yacht8.png",
    gallery: ["interior_cabin.png", "interior_salon.png", "deck_lounge.png", "yacht8.png"]
  },
  "lagoon-spirit": {
    name: "Lagoon Spirit",
    type: "Catamaran",
    price: "€ 1,150,000",
    length: "22m (72')",
    guests: "10 Guests",
    cabins: "5 Cabins",
    year: "2021",
    builder: "Lagoon",
    speed: "11 Knots",
    description: "The ultimate luxury cruising catamaran. Lagoon Spirit offers the interior volume of a 35m motor yacht. Her massive owner's suite occupies an entire hull. With vast outdoor spaces and exceptional stability, she is perfect for extended cruising or luxury charter operations.",
    mainImage: "yacht9.png",
    gallery: ["deck_lounge.png", "interior_salon.png", "interior_cabin.png", "yacht9.png"]
  },
  "la-vita": {
    name: "La Vita",
    type: "Motor Yacht",
    price: "€ 3,900,000",
    length: "32m (105')",
    guests: "10 Guests",
    cabins: "5 Cabins",
    year: "2019",
    builder: "Sanlorenzo",
    speed: "24 Knots",
    description: "Elegant, timeless, and sophisticated. La Vita represents the finest Italian design. Her asymmetrical layout provides a larger main salon and a unique flow between indoor and outdoor spaces. Meticulously maintained and fully equipped for immediate cruising.",
    mainImage: "yacht10.png",
    gallery: ["interior_salon.png", "deck_lounge.png", "interior_cabin.png", "yacht10.png"]
  },
  "arctic-voyager": {
    name: "Arctic Voyager",
    type: "Expedition Yacht",
    price: "€ 11,500,000",
    length: "42m (138')",
    guests: "12 Guests",
    cabins: "6 Cabins",
    year: "2023",
    builder: "Damen Yachting",
    speed: "14 Knots",
    description: "Built for adventure without compromise. Arctic Voyager features an ice-classed hull, a massive 5000nm range, and serious tender carrying capacity. Inside, she offers the luxury of a traditional superyacht with warm woods, cozy fireplaces, and panoramic observation lounges.",
    mainImage: "yacht11.png",
    gallery: ["deck_lounge.png", "interior_cabin.png", "interior_salon.png", "yacht11.png"]
  },
  "aegean-pearl": {
    name: "Aegean Pearl",
    type: "Power Catamaran",
    price: "€ 1,890,000",
    length: "25m (82')",
    guests: "12 Guests",
    cabins: "6 Cabins",
    year: "2022",
    builder: "Sunreef",
    speed: "18 Knots",
    description: "A luxury power catamaran offering unprecedented space and fuel efficiency. Aegean Pearl features a massive full-beam master suite, a hydraulic swimming platform, and a stunning flybridge. Her shallow draft and exceptional stability make her perfect for the Mediterranean.",
    mainImage: "yacht12.png",
    gallery: ["interior_salon.png", "deck_lounge.png", "interior_cabin.png", "yacht12.png"]
  }
};
